language: java
env:
  global:
  - secure: "LJ5/QfUoPbDW+Zk/U1R3BxJ10dfnbcfISZMN0LjRGhc1w2I1omkJ2+vvwNXmI259UVsFnc4NhrqSwuox7VzPf3lMgO1zr2F6oeBWgH7lrvg2vUiKeIHelJFjGl4cOco3OOfQ1RBlfI4GD0rQxu8DOEbKpe2PrUPmWwKvPsFH2nI="
  - secure: "i67ERxJRnd9oSco6ai0JXrbbMoAcpRsvB/TyAYJbnYTRjVj4CLWlu7DNvQghbCK8P2gn3BUH6/XN/KvCPi9GHABNJ8FyZzm81v5fEKmP6dy56KESRZjK8q82jKWxg9cD3O9OAoK00q3QbcjuWlhRiceSDYCFhjxYwPVBFTpabho="
  - secure: "MwjTx+KKbjKjX31dP3Fo5NTkhGkxAa6XG+uj8omhzvwRd0A0YW/NUlhU5QPOartT1X9mJLtuJjq2m5N5q57OtFnblVcD9AjTQeGIuK5WclqunYsQ9HQI8nLo9HEuSrR62OmEjHz2d7q5yDQ/e1yVaYoDlTXpkpOnuDp+wwPKzD0="

addons:
  coverity_scan:
    project:
      name: "hendrens/jdt.spelling"
      description: "Spelling for Java names in eclipse"
    notification_email: stuarthendren@gmail.com
    build_command_prepend:
    build_command: mvn clean verify
    branch_pattern: coverity_scan

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script: mvn verify

after_failure: 
  - cat /home/travis/build/hendrens/jdt.spelling/plugins/jdt.spelling.test/target/work/data/.metadata/.log
  - cat /home/travis/build/hendrens/jdt.spelling/cov-int/build-log.txt
  
after_success: 
  - unzip update/target/jdt.spelling*.zip -d beta && find beta -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.stuarthendren.net/{} \;
  - mvn verify cobertura:cobertura coveralls:cobertura
  - ls -R update

  
